## Bindings for hb-aat-layout.h (HarfBuzz 14.2.1).
##
## Feature types are a Nim enum (values unique). Selector values repeat
## across feature types, so selectors are plain constants over
## hb_aat_layout_feature_selector_t (= cuint). Generated enum/const
## values; procs hand-written below.

import harfbuzz/hb_common
import harfbuzz/hb_face
import harfbuzz/hb_ot_name

export hb_common
export hb_face
export hb_ot_name

type
  hb_aat_layout_feature_type_t* {.size: 4.} = enum
    HB_AAT_LAYOUT_FEATURE_TYPE_INVALID = 0xFFFF
    HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC = 0
    HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES = 1
    HB_AAT_LAYOUT_FEATURE_TYPE_CURSIVE_CONNECTION = 2
    HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE = 3
    HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION = 4
    HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT = 5
    HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING = 6
    HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE = 8
    HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE = 9
    HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION = 10
    HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS = 11
    HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE = 13
    HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS = 14
    HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS = 15
    HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE = 16
    HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES = 17
    HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE = 18
    HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS = 19
    HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE = 20
    HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE = 21
    HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING = 22
    HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION = 23
    HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE = 24
    HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE = 25
    HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE = 26
    HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE = 27
    HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA = 28
    HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE = 29
    HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE = 30
    HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE = 31
    HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN = 32
    HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT = 33
    HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA = 34
    HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES = 35
    HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES = 36
    HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE = 37
    HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE = 38
    HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE = 39
    HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE = 103
    HB_AAT_LAYOUT_FEATURE_TYPE_MAX_VALUE = 0x7FFFFFFF

  hb_aat_layout_feature_selector_t* = cuint

const
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INVALID* = cuint(0xFFFF)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF* = cuint(11)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON* = cuint(12)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF* = cuint(13)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON* = cuint(14)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF* = cuint(15)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON* = cuint(16)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF* = cuint(17)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON* = cuint(18)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF* = cuint(19)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON* = cuint(20)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF* = cuint(21)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF* = cuint(11)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF* = cuint(11)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS* = cuint(11)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS* = cuint(12)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS* = cuint(13)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS* = cuint(14)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON* = cuint(6)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF* = cuint(7)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON* = cuint(8)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF* = cuint(9)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON* = cuint(10)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF* = cuint(11)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON* = cuint(12)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF* = cuint(13)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON* = cuint(14)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF* = cuint(15)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON* = cuint(16)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF* = cuint(17)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON* = cuint(18)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF* = cuint(19)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON* = cuint(20)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF* = cuint(21)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON* = cuint(22)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF* = cuint(23)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON* = cuint(24)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF* = cuint(25)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON* = cuint(26)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF* = cuint(27)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON* = cuint(28)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF* = cuint(29)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON* = cuint(30)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF* = cuint(31)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON* = cuint(32)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF* = cuint(33)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON* = cuint(34)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF* = cuint(35)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON* = cuint(36)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF* = cuint(37)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON* = cuint(38)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF* = cuint(39)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON* = cuint(40)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF* = cuint(41)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF* = cuint(3)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON* = cuint(4)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF* = cuint(5)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN* = cuint(0)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN* = cuint(1)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN* = cuint(2)
  HB_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN* = cuint(3)

type
  hb_aat_layout_feature_selector_info_t* = object
    name_id*: hb_ot_name_id_t
    enable*: hb_aat_layout_feature_selector_t
    disable*: hb_aat_layout_feature_selector_t
    reserved*: cuint

const
  HB_AAT_LAYOUT_NO_SELECTOR_INDEX* = cuint(0xFFFF)

{.push header: "<harfbuzz/hb-aat-layout.h>", importc, cdecl.}

proc hb_aat_layout_get_feature_types*(face: ptr hb_face_t;
                                      start_offset: cuint;
                                      feature_count: ptr cuint;
                                      features: ptr hb_aat_layout_feature_type_t): cuint
proc hb_aat_layout_feature_type_get_name_id*(
    face: ptr hb_face_t;
    feature_type: hb_aat_layout_feature_type_t): hb_ot_name_id_t
proc hb_aat_layout_feature_type_get_selector_infos*(
    face: ptr hb_face_t; feature_type: hb_aat_layout_feature_type_t;
    start_offset: cuint; selector_count: ptr cuint;
    selectors: ptr hb_aat_layout_feature_selector_info_t;
    default_index: ptr cuint): cuint
proc hb_aat_layout_has_substitution*(face: ptr hb_face_t): hb_bool_t
proc hb_aat_layout_has_positioning*(face: ptr hb_face_t): hb_bool_t
proc hb_aat_layout_has_tracking*(face: ptr hb_face_t): hb_bool_t

{.pop.}
